title: 주니의 포폴사이트 
name: JaeHun Jung
email: gaza8@naver.com
description: >-
  Ph.D. City Planning


baseurl: ""
url: "https://juny8.github.io"


# profile 이미지
profile_image: images/about.jpg


# SNS 아이디
#facebook_id: babycheetah
#instagram_id: babycheetah


# Youtube vid
#youtube_vid: #


# Custom Color
primary: b74cf0 #b72cf0
primary_hover: ec5453 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/cover_bg_1.jpg
  title: Real Estate


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/cover_bg_5.jpeg
  title: I am<br>Real Estate Researcher
  subtitle: >- 
    부동산정보 및 통계<br>
    가격추정 AI모델 개발 AI<br>
    부동산 관련 데이터 분석<br>
    부동산 정보 분석 및 Insight 


# Tech  skill
tech_meta: TECH SKILLS

tech_list: # 형식에 맞추어 항목 추가
- name: Stata, SPSS
  color: color-1
  animation: fadeInLeft
  percent: 70
  mark: 70
  content: 시계열자료 분석, Var모형을 통한 동적예측, 다중회귀분석, 이중차이분석, 패널모형분석 등 부동산 통계
- name: Python, R
  color: color-2
  animation: fadeInRight
  percent: 40
  mark: 40
  content: RNN, LSTM, GRU 딥러닝 모델링 구축, 파이썬 언어의 기본적인 문법 알고리즘에 관한 지식
- name: GIS, Geoda
  color: color-3
  animation: fadeInLeft
  percent: 60
  mark: 60
  content: 공간정보를 활용한 Morans'I 및 LISA분석, 공간계량분석, 공간정보를 활용한 자료 구축 및 데이타 분석
- name: Github
  color: color-4
  animation: fadeInRight
  percent: 30
  mark: 30
  content: 프로젝트를 github를 통해 소스 코드 관리 및 협업 진행. github서버를 활용한 포트폴리오 사이트 관리


# Project
project_meta: My Work
project_header: PROJECT
# project_introduce: <span>(1)부동산정보 및 가격 AI모델 개발</span><span>(2)부동산통계 개선 및 신규통계 개발</span><span><br>(3)부동산 관련 데이터 분석 및 관리</span><span>(4)부동산정보 분석 및 Insight 발굴</span><br><br>
project_load_more: 이 밖에도 도시계획 및 교육공간에 관한 다양한 프로젝트와 연구를 수행    # 더보기 내용
project_load_more_url: #

project_my_name: 부동산 정보 및 가격 관련 AI모델 개발

project_my: # 형식에 맞추어 항목 추가
- background_url: images/pj1.PNG
  animation: fadeInLeft
  name: 아파트 실거래가 가격지수 예측
  description: 김경민 교수님 연구실에서 수행된 프로젝트로 국토교통부 아파트 실거래가를 이용하여 공시지가, 공간정보 및 경제변수를 병합, 딥러닝 모형을 사용하여 아파트가격을 추정하는 AI모형을 구축함
  detail_url: images/pj1.PNG
  readmore_url: https://github.com/juny8/deep-learning

- background_url: images/pj2.PNG
  animation: fadeInLeft
  name: 토지입찰시 낙찰 여부 및 낙찰가격 예측
  description: 부동산개발협회와 부동산분석학회의 지원을 받아서 수행되는 이 프로젝트는 공공택지개발사업 지구에서 경쟁입찰로 공급되는 토지입찰의 낙찰 여부 및 낙찰가격을 예측하는 딥러닝 모델을 구축을 목적으로 함
  detail_url: images/pj2.PNG
  readmore_url: https://github.com/juny8/deep-learning

project_team_name: 부동산 통계 개선 및 신규 통계 개발
project_team: # 형식에 맞추어 항목 추가
- background_url: images/pj3.PNG
  animation: fadeInRight
  name: 딥러닝 모형 하이퍼 패러미터 세팅
  description: 딥러닝 모형에서는 정확성을 위한 모형의 피팅이 중요한데, 이를 위하여 For문과 MAPE를 활용한 최적의 하이퍼 패러미터를 세팅하는 모형을 구축함
  detail_url: images/pj3.PNG
  readmore_url: https://github.com/juny8/deep-learning

- background_url: images/pj4.PNG
  animation: fadeInRight
  name: 오피스텔 가격지수 산출
  description: 헤도닉 가격 모형을 활용하여 오피스텔 가격지수를 산출하고 이중차이 분석모형을 이용하여 부동산대책의 효과를 분석함 
  detail_url: images/pj4.PNG
  readmore_url: pdf/pt4.pdf


project_team2_name: 부동산 관련 데이터 분석 및 관리
project_team2: # 형식에 맞추어 항목 추가
- background_url: images/pj5.PNG
  animation: fadeInRight
  name: 주택가격 변동 요인 분석
  description: 부동산 정책 및 기준금리 인상 등의 경제변수 요인에 관한 주택가격 변동 요인을 분석함
  detail_url: images/pj5.PNG
  readmore_url: pdf/pt5.pdf

- background_url: images/pj6.PNG
  animation: fadeInRight
  name: 토지가격 변동 요인 분석
  description: 공공서비스 시설물의 유형을 분류하여 접근성 요인에 관한 토지가격 변동성에 관한 요인분석을 실시
  detail_url: images/pj6.PNG
  readmore_url: pdf/pt6.pdf

project_business_name: 부동산정보 분석 및 Insight 발굴
project_business: # 형식에 맞추어 항목 추가
- background_url: images/pj7.PNG
  animation: fadeInTop
  name: 재정비 지수 산출
  description: >-
    재개발 등 재정비 지역을 발굴하여 정책 우선순위를 판단하기 위한 재정비 잠재력 지수를 산출하여 정책제안을 함
  detail_url: images/pj7.PNG
  readmore_url: pdf/pt7.pdf

  
- background_url: images/pj8.PNG
  animation: fadeInRight
  name: 토지판매위험 진단 및 예측지수 산출
  description: VAR모형을 활용하여 토지 판매위험을 진단하고 동적예측모형을 개발하여 현재 LH는 토지판매 위험지수로 사용하고 있음
  detail_url: images/pj8.PNG
  readmore_url: pdf/pt8.pdf

- background_url: images/pj9.PNG
  animation: fadeInRight
  name: 상업용 부동산의 주거전환 사업모델 검토
  description: 오피스 및 호텔 등의 상업용 부동산을 주거용으로 전환하는 비주거의 주거전환 사업모델을 검토하여 PI, NPV 사업성 분석을 실시하고 제안함 
  detail_url: images/pj9.PNG
  readmore_url: pdf/pt9.pdf





# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: 명지대학교 부동산학과 겸임교수
  date: 현재
  content: 부동산시장분석  <br> 부동산권리분석
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
- name: 서울주택도시공사 연구실 책임연구원
  date: 현재
  content: 도시개발 및 정책연구
  color: color-2
  icon: icon-pen2
  animation: fadeInRight


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: Seoul National UNIVERSITY Doctor's Degree
  subtitle: 서울대학교 도시계획박사
 
 
- title: Seoul National UNIVERSITY Master's Degree
  subtitle: 서울대학교 도시계획석사

 
- title: Seoul National UNIVERSITY
  subtitle: 서울대학교 건축학과

 

optional_front_matter:
  remove_originals:    true
